In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
df = pd.read_csv("../data/raw/data.csv")
df.head()

,diseases,anxiety_and_nervousness,depression,shortness_of_breath,depressive_or_psychotic_symptoms,sharp_chest_pain,dizziness,insomnia,abnormal_involuntary_movements,chest_tightness,palpitations,irregular_heartbeat,breathing_fast,hoarse_voice,sore_throat,difficulty_speaking,cough,nasal_congestion,throat_swelling,diminished_hearing,lump_in_throat,throat_feels_tight,difficulty_in_swallowing,skin_swelling,retention_of_urine,groin_mass,leg_pain,hip_pain,suprapubic_pain,blood_in_stool,lack_of_growth,emotional_symptoms,elbow_weakness,back_weakness,pus_in_sputum,symptoms_of_the_scrotum_and_testes,swelling_of_scrotum,pain_in_testicles,flatulence,pus_draining_from_ear,jaundice,mass_in_scrotum,white_discharge_from_eye,irritable_infant,abusing_alcohol,fainting,hostile_behavior,drug_abuse,sharp_abdominal_pain,feeling_ill,vomiting,headache,nausea,diarrhea,vaginal_itching,vaginal_dryness,painful_urination,involuntary_urination,pain_during_intercourse,frequent_urination,lower_abdominal_pain,vaginal_discharge,blood_in_urine,hot_flashes,intermenstrual_bleeding,hand_or_finger_pain,wrist_pain,hand_or_finger_swelling,arm_pain,wrist_swelling,arm_stiffness_or_tightness,arm_swelling,hand_or_finger_stiffness_or_tightness,wrist_stiffness_or_tightness,lip_swelling,toothache,abnormal_appearing_skin,skin_lesion,acne_or_pimples,dry_lips,facial_pain,mouth_ulcer,skin_growth,eye_deviation,diminished_vision,double_vision,cross_eyed,symptoms_of_eye,pain_in_eye,eye_moves_abnormally,abnormal_movement_of_eyelid,foreign_body_sensation_in_eye,irregular_appearing_scalp,swollen_lymph_nodes,back_pain,neck_pain,low_back_pain,pain_of_the_anus,pain_during_pregnancy,pelvic_pain,impotence,infant_spitting_up,vomiting_blood,regurgitation,burning_abdominal_pain,restlessness,symptoms_of_infants,wheezing,peripheral_edema,neck_mass,ear_pain,jaw_swelling,mouth_dryness,neck_swelling,knee_pain,foot_or_toe_pain,bowlegged_or_knock_kneed,ankle_pain,bones_are_painful,knee_weakness,elbow_pain,knee_swelling,skin_moles,knee_lump_or_mass,weight_gain,problems_with_movement,knee_stiffness_or_tightness,leg_swelling,foot_or_toe_swelling,heartburn,smoking_problems,muscle_pain,infant_feeding_problem,recent_weight_loss,problems_with_shape_or_size_of_breast,underweight,difficulty_eating,scanty_menstrual_flow,vaginal_pain,vaginal_redness,vulvar_irritation,weakness,decreased_heart_rate,increased_heart_rate,bleeding_or_discharge_from_nipple,ringing_in_ear,plugged_feeling_in_ear,itchy_ear_s_,frontal_headache,fluid_in_ear,neck_stiffness_or_tightness,spots_or_clouds_in_vision,eye_redness,lacrimation,itchiness_of_eye,blindness,eye_burns_or_stings,itchy_eyelid,feeling_cold,decreased_appetite,excessive_appetite,excessive_anger,loss_of_sensation,focal_weakness,slurring_words,symptoms_of_the_face,disturbance_of_memory,paresthesia,side_pain,fever,shoulder_pain,shoulder_stiffness_or_tightness,shoulder_weakness,arm_cramps_or_spasms,shoulder_swelling,tongue_lesions,leg_cramps_or_spasms,abnormal_appearing_tongue,ache_all_over,lower_body_pain,problems_during_pregnancy,spotting_or_bleeding_during_pregnancy,cramps_and_spasms,upper_abdominal_pain,stomach_bloating,changes_in_stool_appearance,unusual_color_or_odor_to_urine,kidney_mass,swollen_abdomen,symptoms_of_prostate,leg_stiffness_or_tightness,difficulty_breathing,rib_pain,joint_pain,muscle_stiffness_or_tightness,pallor,hand_or_finger_lump_or_mass,chills,groin_pain,fatigue,abdominal_distention,regurgitation_1,symptoms_of_the_kidneys,melena,flushing,coughing_up_sputum,seizures,delusions_or_hallucinations,shoulder_cramps_or_spasms,joint_stiffness_or_tightness,pain_or_soreness_of_breast,excessive_urination_at_night,bleeding_from_eye,rectal_bleeding,constipation,temper_problems,coryza,wrist_weakness,eye_strain,hemoptysis,lymphedema,skin_on_leg_or_foot_looks_infected,allergic_reaction,congestion_in_chest,muscle_swelling,pus_in_urine,abnormal_size_or_shape_of_ear,low_back_weakness,sleepiness,apnea,abnormal_breathing_sounds,excessive_growth,elbow_cramps_or_spasms,feeling_hot_and_cold,blood_clots_during_menstrual_periods,absence_of_menstruation,pulling_at_ears,gum_pain,redness_in_ear,fluid_retention,flu_like_syndrome,sinus_congestion,painful_sinuses,fears_and_phobias,recent_pregnancy,uterine_contractions,burning_chest_pain,back_cramps_or_spasms,stiffness_all_over,muscle_cramps_contractures_or_spasms,low_back_cramps_or_spasms,back_mass_or_lump,nosebleed,long_menstrual_periods,heavy_menstrual_flow,unpredictable_menstruation,painful_menstruation,infertility,frequent_menstruation,sweating,mass_on_eyelid,swollen_eye,eyelid_swelling,eyelid_lesion_or_rash,unwanted_hair,symptoms_of_bladder,irregular_appearing_nails,itching_of_skin,hurts_to_breath,nailbiting,skin_dryness_peeling_scaliness_or_roughness,skin_on_arm_or_hand_looks_infected,skin_irritation,itchy_scalp,hip_swelling,incontinence_of_stool,foot_or_toe_cramps_or_spasms,warts,bumps_on_penis,too_little_hair,foot_or_toe_lump_or_mass,skin_rash,mass_or_swelling_around_the_anus,low_back_swelling,ankle_swelling,hip_lump_or_mass,drainage_in_throat,dry_or_flaky_scalp,premenstrual_tension_or_irritability,feeling_hot,feet_turned_in,foot_or_toe_stiffness_or_tightness,pelvic_pressure,elbow_swelling,elbow_stiffness_or_tightness,early_or_late_onset_of_menopause,mass_on_ear,bleeding_from_ear,hand_or_finger_weakness,low_self_esteem,throat_irritation,itching_of_the_anus,swollen_or_red_tonsils,irregular_belly_button,swollen_tongue,lip_sore,vulvar_sore,hip_stiffness_or_tightness,mouth_pain,arm_weakness,leg_lump_or_mass,disturbance_of_smell_or_taste,discharge_in_stools,penis_pain,loss_of_sex_drive,obsessions_and_compulsions,antisocial_behavior,neck_cramps_or_spasms,pupils_unequal,poor_circulation,thirst,sleepwalking,skin_oiliness,sneezing,bladder_mass,knee_cramps_or_spasms,premature_ejaculation,leg_weakness,posture_problems,bleeding_in_mouth,tongue_bleeding,change_in_skin_mole_size_or_color,penis_redness,penile_discharge,shoulder_lump_or_mass,polyuria,cloudy_eye,hysterical_behavior,arm_lump_or_mass,nightmares,bleeding_gums,pain_in_gums,bedwetting,diaper_rash,lump_or_mass_of_breast,vaginal_bleeding_after_menopause,infrequent_menstruation,mass_on_vulva,jaw_pain,itching_of_scrotum,postpartum_problems_of_the_breast,eyelid_retracted,hesitancy,elbow_lump_or_mass,muscle_weakness,throat_redness,joint_swelling,tongue_pain,redness_in_or_around_nose,wrinkles_on_skin,foot_or_toe_weakness,hand_or_finger_cramps_or_spasms,back_stiffness_or_tightness,wrist_lump_or_mass,skin_pain,low_back_stiffness_or_tightness,low_urine_output,skin_on_head_or_neck_looks_infected,stuttering_or_stammering,problems_with_orgasm,nose_deformity,lump_over_jaw,sore_in_nose,hip_weakness,back_swelling,ankle_stiffness_or_tightness,ankle_weakness,neck_weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [3]:
df.tail()

,diseases,anxiety_and_nervousness,depression,shortness_of_breath,depressive_or_psychotic_symptoms,sharp_chest_pain,dizziness,insomnia,abnormal_involuntary_movements,chest_tightness,palpitations,irregular_heartbeat,breathing_fast,hoarse_voice,sore_throat,difficulty_speaking,cough,nasal_congestion,throat_swelling,diminished_hearing,lump_in_throat,throat_feels_tight,difficulty_in_swallowing,skin_swelling,retention_of_urine,groin_mass,leg_pain,hip_pain,suprapubic_pain,blood_in_stool,lack_of_growth,emotional_symptoms,elbow_weakness,back_weakness,pus_in_sputum,symptoms_of_the_scrotum_and_testes,swelling_of_scrotum,pain_in_testicles,flatulence,pus_draining_from_ear,jaundice,mass_in_scrotum,white_discharge_from_eye,irritable_infant,abusing_alcohol,fainting,hostile_behavior,drug_abuse,sharp_abdominal_pain,feeling_ill,vomiting,headache,nausea,diarrhea,vaginal_itching,vaginal_dryness,painful_urination,involuntary_urination,pain_during_intercourse,frequent_urination,lower_abdominal_pain,vaginal_discharge,blood_in_urine,hot_flashes,intermenstrual_bleeding,hand_or_finger_pain,wrist_pain,hand_or_finger_swelling,arm_pain,wrist_swelling,arm_stiffness_or_tightness,arm_swelling,hand_or_finger_stiffness_or_tightness,wrist_stiffness_or_tightness,lip_swelling,toothache,abnormal_appearing_skin,skin_lesion,acne_or_pimples,dry_lips,facial_pain,mouth_ulcer,skin_growth,eye_deviation,diminished_vision,double_vision,cross_eyed,symptoms_of_eye,pain_in_eye,eye_moves_abnormally,abnormal_movement_of_eyelid,foreign_body_sensation_in_eye,irregular_appearing_scalp,swollen_lymph_nodes,back_pain,neck_pain,low_back_pain,pain_of_the_anus,pain_during_pregnancy,pelvic_pain,impotence,infant_spitting_up,vomiting_blood,regurgitation,burning_abdominal_pain,restlessness,symptoms_of_infants,wheezing,peripheral_edema,neck_mass,ear_pain,jaw_swelling,mouth_dryness,neck_swelling,knee_pain,foot_or_toe_pain,bowlegged_or_knock_kneed,ankle_pain,bones_are_painful,knee_weakness,elbow_pain,knee_swelling,skin_moles,knee_lump_or_mass,weight_gain,problems_with_movement,knee_stiffness_or_tightness,leg_swelling,foot_or_toe_swelling,heartburn,smoking_problems,muscle_pain,infant_feeding_problem,recent_weight_loss,problems_with_shape_or_size_of_breast,underweight,difficulty_eating,scanty_menstrual_flow,vaginal_pain,vaginal_redness,vulvar_irritation,weakness,decreased_heart_rate,increased_heart_rate,bleeding_or_discharge_from_nipple,ringing_in_ear,plugged_feeling_in_ear,itchy_ear_s_,frontal_headache,fluid_in_ear,neck_stiffness_or_tightness,spots_or_clouds_in_vision,eye_redness,lacrimation,itchiness_of_eye,blindness,eye_burns_or_stings,itchy_eyelid,feeling_cold,decreased_appetite,excessive_appetite,excessive_anger,loss_of_sensation,focal_weakness,slurring_words,symptoms_of_the_face,disturbance_of_memory,paresthesia,side_pain,fever,shoulder_pain,shoulder_stiffness_or_tightness,shoulder_weakness,arm_cramps_or_spasms,shoulder_swelling,tongue_lesions,leg_cramps_or_spasms,abnormal_appearing_tongue,ache_all_over,lower_body_pain,problems_during_pregnancy,spotting_or_bleeding_during_pregnancy,cramps_and_spasms,upper_abdominal_pain,stomach_bloating,changes_in_stool_appearance,unusual_color_or_odor_to_urine,kidney_mass,swollen_abdomen,symptoms_of_prostate,leg_stiffness_or_tightness,difficulty_breathing,rib_pain,joint_pain,muscle_stiffness_or_tightness,pallor,hand_or_finger_lump_or_mass,chills,groin_pain,fatigue,abdominal_distention,regurgitation_1,symptoms_of_the_kidneys,melena,flushing,coughing_up_sputum,seizures,delusions_or_hallucinations,shoulder_cramps_or_spasms,joint_stiffness_or_tightness,pain_or_soreness_of_breast,excessive_urination_at_night,bleeding_from_eye,rectal_bleeding,constipation,temper_problems,coryza,wrist_weakness,eye_strain,hemoptysis,lymphedema,skin_on_leg_or_foot_looks_infected,allergic_reaction,congestion_in_chest,muscle_swelling,pus_in_urine,abnormal_size_or_shape_of_ear,low_back_weakness,sleepiness,apnea,abnormal_breathing_sounds,excessive_growth,elbow_cramps_or_spasms,feeling_hot_and_cold,blood_clots_during_menstrual_periods,absence_of_menstruation,pulling_at_ears,gum_pain,redness_in_ear,fluid_retention,flu_like_syndrome,sinus_congestion,painful_sinuses,fears_and_phobias,recent_pregnancy,uterine_contractions,burning_chest_pain,back_cramps_or_spasms,stiffness_all_over,muscle_cramps_contractures_or_spasms,low_back_cramps_or_spasms,back_mass_or_lump,nosebleed,long_menstrual_periods,heavy_menstrual_flow,unpredictable_menstruation,painful_menstruation,infertility,frequent_menstruation,sweating,mass_on_eyelid,swollen_eye,eyelid_swelling,eyelid_lesion_or_rash,unwanted_hair,symptoms_of_bladder,irregular_appearing_nails,itching_of_skin,hurts_to_breath,nailbiting,skin_dryness_peeling_scaliness_or_roughness,skin_on_arm_or_hand_looks_infected,skin_irritation,itchy_scalp,hip_swelling,incontinence_of_stool,foot_or_toe_cramps_or_spasms,warts,bumps_on_penis,too_little_hair,foot_or_toe_lump_or_mass,skin_rash,mass_or_swelling_around_the_anus,low_back_swelling,ankle_swelling,hip_lump_or_mass,drainage_in_throat,dry_or_flaky_scalp,premenstrual_tension_or_irritability,feeling_hot,feet_turned_in,foot_or_toe_stiffness_or_tightness,pelvic_pressure,elbow_swelling,elbow_stiffness_or_tightness,early_or_late_onset_of_menopause,mass_on_ear,bleeding_from_ear,hand_or_finger_weakness,low_self_esteem,throat_irritation,itching_of_the_anus,swollen_or_red_tonsils,irregular_belly_button,swollen_tongue,lip_sore,vulvar_sore,hip_stiffness_or_tightness,mouth_pain,arm_weakness,leg_lump_or_mass,disturbance_of_smell_or_taste,discharge_in_stools,penis_pain,loss_of_sex_drive,obsessions_and_compulsions,antisocial_behavior,neck_cramps_or_spasms,pupils_unequal,poor_circulation,thirst,sleepwalking,skin_oiliness,sneezing,bladder_mass,knee_cramps_or_spasms,premature_ejaculation,leg_weakness,posture_problems,bleeding_in_mouth,tongue_bleeding,change_in_skin_mole_size_or_color,penis_redness,penile_discharge,shoulder_lump_or_mass,polyuria,cloudy_eye,hysterical_behavior,arm_lump_or_mass,nightmares,bleeding_gums,pain_in_gums,bedwetting,diaper_rash,lump_or_mass_of_breast,vaginal_bleeding_after_menopause,infrequent_menstruation,mass_on_vulva,jaw_pain,itching_of_scrotum,postpartum_problems_of_the_breast,eyelid_retracted,hesitancy,elbow_lump_or_mass,muscle_weakness,throat_redness,joint_swelling,tongue_pain,redness_in_or_around_nose,wrinkles_on_skin,foot_or_toe_weakness,hand_or_finger_cramps_or_spasms,back_stiffness_or_tightness,wrist_lump_or_mass,skin_pain,low_back_stiffness_or_tightness,low_urine_output,skin_on_head_or_neck_looks_infected,stuttering_or_stammering,problems_with_orgasm,nose_deformity,lump_over_jaw,sore_in_nose,hip_weakness,back_swelling,ankle_stiffness_or_tightness,ankle_weakness,neck_weakness
246940,open wound of the nose,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
246941,open wound of the nose,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
246942,open wound of the nose,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
246943,open wound of the nose,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
246944,open wound of the nose,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
df.shape

(246945, 378)

In [5]:
df.columns

Index(['diseases', 'anxiety_and_nervousness', 'depression',
       'shortness_of_breath', 'depressive_or_psychotic_symptoms',
       'sharp_chest_pain', 'dizziness', 'insomnia',
       'abnormal_involuntary_movements', 'chest_tightness',
       ...
       'stuttering_or_stammering', 'problems_with_orgasm', 'nose_deformity',
       'lump_over_jaw', 'sore_in_nose', 'hip_weakness', 'back_swelling',
       'ankle_stiffness_or_tightness', 'ankle_weakness', 'neck_weakness'],
      dtype='str', length=378)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246945 entries, 0 to 246944
Columns: 378 entries, diseases to neck_weakness
dtypes: int64(377), str(1)
memory usage: 716.3 MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
anxiety_and_nervousness,246945.0,0.039235,0.194155,0.0,0.0,0.0,0.0,1.0
depression,246945.0,0.042746,0.202285,0.0,0.0,0.0,0.0,1.0
shortness_of_breath,246945.0,0.086440,0.281014,0.0,0.0,0.0,0.0,1.0
depressive_or_psychotic_symptoms,246945.0,0.061001,0.239333,0.0,0.0,0.0,0.0,1.0
sharp_chest_pain,246945.0,0.097252,0.296302,0.0,0.0,0.0,0.0,1.0
dizziness,246945.0,0.069943,0.255051,0.0,0.0,0.0,0.0,1.0
insomnia,246945.0,0.039410,0.194568,0.0,0.0,0.0,0.0,1.0
abnormal_involuntary_movements,246945.0,0.040572,0.197296,0.0,0.0,0.0,0.0,1.0
chest_tightness,246945.0,0.037871,0.190884,0.0,0.0,0.0,0.0,1.0
palpitations,246945.0,0.024876,0.155747,0.0,0.0,0.0,0.0,1.0
irregular_heartbeat,246945.0,0.025111,0.156462,0.0,0.0,0.0,0.0,1.0
breathing_fast,246945.0,0.001895,0.043492,0.0,0.0,0.0,0.0,1.0
hoarse_voice,246945.0,0.013460,0.115236,0.0,0.0,0.0,0.0,1.0
sore_throat,246945.0,0.056713,0.231294,0.0,0.0,0.0,0.0,1.0
difficulty_speaking,246945.0,0.025066,0.156327,0.0,0.0,0.0,0.0,1.0
cough,246945.0,0.098386,0.297837,0.0,0.0,0.0,0.0,1.0
nasal_congestion,246945.0,0.065602,0.247585,0.0,0.0,0.0,0.0,1.0
throat_swelling,246945.0,0.007326,0.085275,0.0,0.0,0.0,0.0,1.0
diminished_hearing,246945.0,0.022058,0.146871,0.0,0.0,0.0,0.0,1.0
lump_in_throat,246945.0,0.002106,0.045840,0.0,0.0,0.0,0.0,1.0
throat_feels_tight,246945.0,0.009751,0.098266,0.0,0.0,0.0,0.0,1.0
difficulty_in_swallowing,246945.0,0.022527,0.148391,0.0,0.0,0.0,0.0,1.0
skin_swelling,246945.0,0.061410,0.240082,0.0,0.0,0.0,0.0,1.0
retention_of_urine,246945.0,0.033740,0.180560,0.0,0.0,0.0,0.0,1.0
groin_mass,246945.0,0.008273,0.090580,0.0,0.0,0.0,0.0,1.0
leg_pain,246945.0,0.065557,0.247507,0.0,0.0,0.0,0.0,1.0
hip_pain,246945.0,0.038968,0.193520,0.0,0.0,0.0,0.0,1.0
suprapubic_pain,246945.0,0.033712,0.180487,0.0,0.0,0.0,0.0,1.0
blood_in_stool,246945.0,0.030092,0.170840,0.0,0.0,0.0,0.0,1.0
lack_of_growth,246945.0,0.013327,0.114670,0.0,0.0,0.0,0.0,1.0
emotional_symptoms,246945.0,0.002527,0.050205,0.0,0.0,0.0,0.0,1.0
elbow_weakness,246945.0,0.001353,0.036752,0.0,0.0,0.0,0.0,1.0
back_weakness,246945.0,0.001195,0.034542,0.0,0.0,0.0,0.0,1.0
pus_in_sputum,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
symptoms_of_the_scrotum_and_testes,246945.0,0.008488,0.091737,0.0,0.0,0.0,0.0,1.0
swelling_of_scrotum,246945.0,0.007467,0.086090,0.0,0.0,0.0,0.0,1.0
pain_in_testicles,246945.0,0.009954,0.099270,0.0,0.0,0.0,0.0,1.0
flatulence,246945.0,0.003564,0.059589,0.0,0.0,0.0,0.0,1.0
pus_draining_from_ear,246945.0,0.003215,0.056612,0.0,0.0,0.0,0.0,1.0
jaundice,246945.0,0.006414,0.079833,0.0,0.0,0.0,0.0,1.0
mass_in_scrotum,246945.0,0.005240,0.072198,0.0,0.0,0.0,0.0,1.0
white_discharge_from_eye,246945.0,0.013056,0.113513,0.0,0.0,0.0,0.0,1.0
irritable_infant,246945.0,0.009051,0.094703,0.0,0.0,0.0,0.0,1.0
abusing_alcohol,246945.0,0.029278,0.168584,0.0,0.0,0.0,0.0,1.0
fainting,246945.0,0.028233,0.165638,0.0,0.0,0.0,0.0,1.0
hostile_behavior,246945.0,0.032319,0.176846,0.0,0.0,0.0,0.0,1.0
drug_abuse,246945.0,0.021657,0.145560,0.0,0.0,0.0,0.0,1.0
sharp_abdominal_pain,246945.0,0.130827,0.337211,0.0,0.0,0.0,0.0,1.0
feeling_ill,246945.0,0.017559,0.131341,0.0,0.0,0.0,0.0,1.0
vomiting,246945.0,0.112875,0.316441,0.0,0.0,0.0,0.0,1.0
headache,246945.0,0.100099,0.300133,0.0,0.0,0.0,0.0,1.0
nausea,246945.0,0.095920,0.294482,0.0,0.0,0.0,0.0,1.0
diarrhea,246945.0,0.042406,0.201514,0.0,0.0,0.0,0.0,1.0
vaginal_itching,246945.0,0.021300,0.144384,0.0,0.0,0.0,0.0,1.0
vaginal_dryness,246945.0,0.001267,0.035579,0.0,0.0,0.0,0.0,1.0
painful_urination,246945.0,0.034963,0.183687,0.0,0.0,0.0,0.0,1.0
involuntary_urination,246945.0,0.025419,0.157393,0.0,0.0,0.0,0.0,1.0
pain_during_intercourse,246945.0,0.005912,0.076664,0.0,0.0,0.0,0.0,1.0
frequent_urination,246945.0,0.029112,0.168120,0.0,0.0,0.0,0.0,1.0
lower_abdominal_pain,246945.0,0.060483,0.238380,0.0,0.0,0.0,0.0,1.0
vaginal_discharge,246945.0,0.027184,0.162620,0.0,0.0,0.0,0.0,1.0
blood_in_urine,246945.0,0.026804,0.161509,0.0,0.0,0.0,0.0,1.0
hot_flashes,246945.0,0.007313,0.085205,0.0,0.0,0.0,0.0,1.0
intermenstrual_bleeding,246945.0,0.025795,0.158524,0.0,0.0,0.0,0.0,1.0
hand_or_finger_pain,246945.0,0.027763,0.164294,0.0,0.0,0.0,0.0,1.0
wrist_pain,246945.0,0.019757,0.139166,0.0,0.0,0.0,0.0,1.0
hand_or_finger_swelling,246945.0,0.019438,0.138057,0.0,0.0,0.0,0.0,1.0
arm_pain,246945.0,0.047051,0.211748,0.0,0.0,0.0,0.0,1.0
wrist_swelling,246945.0,0.014222,0.118404,0.0,0.0,0.0,0.0,1.0
arm_stiffness_or_tightness,246945.0,0.010006,0.099530,0.0,0.0,0.0,0.0,1.0
arm_swelling,246945.0,0.012691,0.111938,0.0,0.0,0.0,0.0,1.0
hand_or_finger_stiffness_or_tightness,246945.0,0.007293,0.085088,0.0,0.0,0.0,0.0,1.0
wrist_stiffness_or_tightness,246945.0,0.001033,0.032118,0.0,0.0,0.0,0.0,1.0
lip_swelling,246945.0,0.023710,0.152144,0.0,0.0,0.0,0.0,1.0
toothache,246945.0,0.010824,0.103475,0.0,0.0,0.0,0.0,1.0
abnormal_appearing_skin,246945.0,0.066513,0.249177,0.0,0.0,0.0,0.0,1.0
skin_lesion,246945.0,0.049971,0.217885,0.0,0.0,0.0,0.0,1.0
acne_or_pimples,246945.0,0.032461,0.177220,0.0,0.0,0.0,0.0,1.0
dry_lips,246945.0,0.001478,0.038417,0.0,0.0,0.0,0.0,1.0
facial_pain,246945.0,0.032845,0.178232,0.0,0.0,0.0,0.0,1.0
mouth_ulcer,246945.0,0.012229,0.109909,0.0,0.0,0.0,0.0,1.0
skin_growth,246945.0,0.041754,0.200027,0.0,0.0,0.0,0.0,1.0
eye_deviation,246945.0,0.003483,0.058910,0.0,0.0,0.0,0.0,1.0
diminished_vision,246945.0,0.035502,0.185045,0.0,0.0,0.0,0.0,1.0
double_vision,246945.0,0.018559,0.134961,0.0,0.0,0.0,0.0,1.0
cross_eyed,246945.0,0.001280,0.035749,0.0,0.0,0.0,0.0,1.0
symptoms_of_eye,246945.0,0.033906,0.180988,0.0,0.0,0.0,0.0,1.0
pain_in_eye,246945.0,0.038280,0.191871,0.0,0.0,0.0,0.0,1.0
eye_moves_abnormally,246945.0,0.002195,0.046798,0.0,0.0,0.0,0.0,1.0
abnormal_movement_of_eyelid,246945.0,0.008431,0.091433,0.0,0.0,0.0,0.0,1.0
foreign_body_sensation_in_eye,246945.0,0.022260,0.147528,0.0,0.0,0.0,0.0,1.0
irregular_appearing_scalp,246945.0,0.032485,0.177285,0.0,0.0,0.0,0.0,1.0
swollen_lymph_nodes,246945.0,0.007597,0.086828,0.0,0.0,0.0,0.0,1.0
back_pain,246945.0,0.088315,0.283753,0.0,0.0,0.0,0.0,1.0
neck_pain,246945.0,0.041459,0.199349,0.0,0.0,0.0,0.0,1.0
low_back_pain,246945.0,0.044759,0.206775,0.0,0.0,0.0,0.0,1.0
pain_of_the_anus,246945.0,0.013201,0.114136,0.0,0.0,0.0,0.0,1.0
pain_during_pregnancy,246945.0,0.021049,0.143549,0.0,0.0,0.0,0.0,1.0
pelvic_pain,246945.0,0.038336,0.192008,0.0,0.0,0.0,0.0,1.0
impotence,246945.0,0.009840,0.098709,0.0,0.0,0.0,0.0,1.0
infant_spitting_up,246945.0,0.000324,0.017996,0.0,0.0,0.0,0.0,1.0
vomiting_blood,246945.0,0.013416,0.115048,0.0,0.0,0.0,0.0,1.0
regurgitation,246945.0,0.010083,0.099908,0.0,0.0,0.0,0.0,1.0
burning_abdominal_pain,246945.0,0.052566,0.223167,0.0,0.0,0.0,0.0,1.0
restlessness,246945.0,0.010022,0.099610,0.0,0.0,0.0,0.0,1.0
symptoms_of_infants,246945.0,0.000960,0.030965,0.0,0.0,0.0,0.0,1.0
wheezing,246945.0,0.019676,0.138886,0.0,0.0,0.0,0.0,1.0
peripheral_edema,246945.0,0.035214,0.184321,0.0,0.0,0.0,0.0,1.0
neck_mass,246945.0,0.008160,0.089962,0.0,0.0,0.0,0.0,1.0
ear_pain,246945.0,0.042860,0.202541,0.0,0.0,0.0,0.0,1.0
jaw_swelling,246945.0,0.009456,0.096779,0.0,0.0,0.0,0.0,1.0
mouth_dryness,246945.0,0.003900,0.062325,0.0,0.0,0.0,0.0,1.0
neck_swelling,246945.0,0.008852,0.093669,0.0,0.0,0.0,0.0,1.0
knee_pain,246945.0,0.032481,0.177274,0.0,0.0,0.0,0.0,1.0
foot_or_toe_pain,246945.0,0.028699,0.166959,0.0,0.0,0.0,0.0,1.0
bowlegged_or_knock_kneed,246945.0,0.000247,0.015715,0.0,0.0,0.0,0.0,1.0
ankle_pain,246945.0,0.016182,0.126174,0.0,0.0,0.0,0.0,1.0
bones_are_painful,246945.0,0.015813,0.124753,0.0,0.0,0.0,0.0,1.0
knee_weakness,246945.0,0.004693,0.068347,0.0,0.0,0.0,0.0,1.0
elbow_pain,246945.0,0.019308,0.137605,0.0,0.0,0.0,0.0,1.0
knee_swelling,246945.0,0.015420,0.123218,0.0,0.0,0.0,0.0,1.0
skin_moles,246945.0,0.025783,0.158488,0.0,0.0,0.0,0.0,1.0
knee_lump_or_mass,246945.0,0.003928,0.062551,0.0,0.0,0.0,0.0,1.0
weight_gain,246945.0,0.012059,0.109151,0.0,0.0,0.0,0.0,1.0
problems_with_movement,246945.0,0.036032,0.186371,0.0,0.0,0.0,0.0,1.0
knee_stiffness_or_tightness,246945.0,0.005062,0.070967,0.0,0.0,0.0,0.0,1.0
leg_swelling,246945.0,0.024244,0.153807,0.0,0.0,0.0,0.0,1.0
foot_or_toe_swelling,246945.0,0.017267,0.130265,0.0,0.0,0.0,0.0,1.0
heartburn,246945.0,0.028156,0.165419,0.0,0.0,0.0,0.0,1.0
smoking_problems,246945.0,0.007961,0.088870,0.0,0.0,0.0,0.0,1.0
muscle_pain,246945.0,0.007471,0.086113,0.0,0.0,0.0,0.0,1.0
infant_feeding_problem,246945.0,0.002944,0.054179,0.0,0.0,0.0,0.0,1.0
recent_weight_loss,246945.0,0.000591,0.024308,0.0,0.0,0.0,0.0,1.0
problems_with_shape_or_size_of_breast,246945.0,0.000190,0.013795,0.0,0.0,0.0,0.0,1.0
underweight,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
difficulty_eating,246945.0,0.001393,0.037297,0.0,0.0,0.0,0.0,1.0
scanty_menstrual_flow,246945.0,0.000049,0.006971,0.0,0.0,0.0,0.0,1.0
vaginal_pain,246945.0,0.011784,0.107913,0.0,0.0,0.0,0.0,1.0
vaginal_redness,246945.0,0.005163,0.071669,0.0,0.0,0.0,0.0,1.0
vulvar_irritation,246945.0,0.002199,0.046841,0.0,0.0,0.0,0.0,1.0
weakness,246945.0,0.046776,0.211158,0.0,0.0,0.0,0.0,1.0
decreased_heart_rate,246945.0,0.008872,0.093775,0.0,0.0,0.0,0.0,1.0
increased_heart_rate,246945.0,0.012877,0.112746,0.0,0.0,0.0,0.0,1.0
bleeding_or_discharge_from_nipple,246945.0,0.001320,0.036310,0.0,0.0,0.0,0.0,1.0
ringing_in_ear,246945.0,0.011023,0.104409,0.0,0.0,0.0,0.0,1.0
plugged_feeling_in_ear,246945.0,0.017146,0.129814,0.0,0.0,0.0,0.0,1.0
itchy_ear_s_,246945.0,0.004896,0.069799,0.0,0.0,0.0,0.0,1.0
frontal_headache,246945.0,0.007277,0.084994,0.0,0.0,0.0,0.0,1.0
fluid_in_ear,246945.0,0.012768,0.112272,0.0,0.0,0.0,0.0,1.0
neck_stiffness_or_tightness,246945.0,0.004503,0.066953,0.0,0.0,0.0,0.0,1.0
spots_or_clouds_in_vision,246945.0,0.021142,0.143859,0.0,0.0,0.0,0.0,1.0
eye_redness,246945.0,0.024609,0.154930,0.0,0.0,0.0,0.0,1.0
lacrimation,246945.0,0.029658,0.169644,0.0,0.0,0.0,0.0,1.0
itchiness_of_eye,246945.0,0.027941,0.164805,0.0,0.0,0.0,0.0,1.0
blindness,246945.0,0.007520,0.086391,0.0,0.0,0.0,0.0,1.0
eye_burns_or_stings,246945.0,0.012476,0.110999,0.0,0.0,0.0,0.0,1.0
itchy_eyelid,246945.0,0.002065,0.045398,0.0,0.0,0.0,0.0,1.0
feeling_cold,246945.0,0.000405,0.020119,0.0,0.0,0.0,0.0,1.0
decreased_appetite,246945.0,0.028229,0.165627,0.0,0.0,0.0,0.0,1.0
excessive_appetite,246945.0,0.002405,0.048986,0.0,0.0,0.0,0.0,1.0
excessive_anger,246945.0,0.027666,0.164015,0.0,0.0,0.0,0.0,1.0
loss_of_sensation,246945.0,0.042111,0.200842,0.0,0.0,0.0,0.0,1.0
focal_weakness,246945.0,0.011816,0.108059,0.0,0.0,0.0,0.0,1.0
slurring_words,246945.0,0.007062,0.083740,0.0,0.0,0.0,0.0,1.0
symptoms_of_the_face,246945.0,0.009249,0.095726,0.0,0.0,0.0,0.0,1.0
disturbance_of_memory,246945.0,0.021410,0.144746,0.0,0.0,0.0,0.0,1.0
paresthesia,246945.0,0.026597,0.160903,0.0,0.0,0.0,0.0,1.0
side_pain,246945.0,0.042544,0.201827,0.0,0.0,0.0,0.0,1.0
fever,246945.0,0.082585,0.275255,0.0,0.0,0.0,0.0,1.0
shoulder_pain,246945.0,0.031460,0.174559,0.0,0.0,0.0,0.0,1.0
shoulder_stiffness_or_tightness,246945.0,0.006313,0.079204,0.0,0.0,0.0,0.0,1.0
shoulder_weakness,246945.0,0.000782,0.027945,0.0,0.0,0.0,0.0,1.0
arm_cramps_or_spasms,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
shoulder_swelling,246945.0,0.000591,0.024308,0.0,0.0,0.0,0.0,1.0
tongue_lesions,246945.0,0.004041,0.063443,0.0,0.0,0.0,0.0,1.0
leg_cramps_or_spasms,246945.0,0.007937,0.088736,0.0,0.0,0.0,0.0,1.0
abnormal_appearing_tongue,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
ache_all_over,246945.0,0.029492,0.169182,0.0,0.0,0.0,0.0,1.0
lower_body_pain,246945.0,0.030493,0.171939,0.0,0.0,0.0,0.0,1.0
problems_during_pregnancy,246945.0,0.017190,0.129979,0.0,0.0,0.0,0.0,1.0
spotting_or_bleeding_during_pregnancy,246945.0,0.010877,0.103724,0.0,0.0,0.0,0.0,1.0
cramps_and_spasms,246945.0,0.021936,0.146475,0.0,0.0,0.0,0.0,1.0
upper_abdominal_pain,246945.0,0.025844,0.158670,0.0,0.0,0.0,0.0,1.0
stomach_bloating,246945.0,0.008949,0.094177,0.0,0.0,0.0,0.0,1.0
changes_in_stool_appearance,246945.0,0.009601,0.097515,0.0,0.0,0.0,0.0,1.0
unusual_color_or_odor_to_urine,246945.0,0.003770,0.061285,0.0,0.0,0.0,0.0,1.0
kidney_mass,246945.0,0.002422,0.049150,0.0,0.0,0.0,0.0,1.0
swollen_abdomen,246945.0,0.002640,0.051316,0.0,0.0,0.0,0.0,1.0
symptoms_of_prostate,246945.0,0.006066,0.077649,0.0,0.0,0.0,0.0,1.0
leg_stiffness_or_tightness,246945.0,0.005410,0.073354,0.0,0.0,0.0,0.0,1.0
difficulty_breathing,246945.0,0.032914,0.178412,0.0,0.0,0.0,0.0,1.0
rib_pain,246945.0,0.008172,0.090028,0.0,0.0,0.0,0.0,1.0
joint_pain,246945.0,0.017595,0.131474,0.0,0.0,0.0,0.0,1.0
muscle_stiffness_or_tightness,246945.0,0.000749,0.027360,0.0,0.0,0.0,0.0,1.0
pallor,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
hand_or_finger_lump_or_mass,246945.0,0.004102,0.063916,0.0,0.0,0.0,0.0,1.0
chills,246945.0,0.025406,0.157357,0.0,0.0,0.0,0.0,1.0
groin_pain,246945.0,0.009780,0.098407,0.0,0.0,0.0,0.0,1.0
fatigue,246945.0,0.025103,0.156438,0.0,0.0,0.0,0.0,1.0
abdominal_distention,246945.0,0.000741,0.027212,0.0,0.0,0.0,0.0,1.0
regurgitation_1,246945.0,0.016886,0.128846,0.0,0.0,0.0,0.0,1.0
symptoms_of_the_kidneys,246945.0,0.005220,0.072059,0.0,0.0,0.0,0.0,1.0
melena,246945.0,0.008423,0.091389,0.0,0.0,0.0,0.0,1.0
flushing,246945.0,0.000373,0.019298,0.0,0.0,0.0,0.0,1.0
coughing_up_sputum,246945.0,0.010865,0.103667,0.0,0.0,0.0,0.0,1.0
seizures,246945.0,0.015558,0.123758,0.0,0.0,0.0,0.0,1.0
delusions_or_hallucinations,246945.0,0.029015,0.167848,0.0,0.0,0.0,0.0,1.0
shoulder_cramps_or_spasms,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
joint_stiffness_or_tightness,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
pain_or_soreness_of_breast,246945.0,0.002652,0.051433,0.0,0.0,0.0,0.0,1.0
excessive_urination_at_night,246945.0,0.007058,0.083717,0.0,0.0,0.0,0.0,1.0
bleeding_from_eye,246945.0,0.002413,0.049068,0.0,0.0,0.0,0.0,1.0
rectal_bleeding,246945.0,0.017546,0.131296,0.0,0.0,0.0,0.0,1.0
constipation,246945.0,0.015275,0.122643,0.0,0.0,0.0,0.0,1.0
temper_problems,246945.0,0.027298,0.162949,0.0,0.0,0.0,0.0,1.0
coryza,246945.0,0.031865,0.175642,0.0,0.0,0.0,0.0,1.0
wrist_weakness,246945.0,0.000016,0.004025,0.0,0.0,0.0,0.0,1.0
eye_strain,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
hemoptysis,246945.0,0.008702,0.092880,0.0,0.0,0.0,0.0,1.0
lymphedema,246945.0,0.010873,0.103705,0.0,0.0,0.0,0.0,1.0
skin_on_leg_or_foot_looks_infected,246945.0,0.005860,0.076324,0.0,0.0,0.0,0.0,1.0
allergic_reaction,246945.0,0.024017,0.153104,0.0,0.0,0.0,0.0,1.0
congestion_in_chest,246945.0,0.005738,0.075533,0.0,0.0,0.0,0.0,1.0
muscle_swelling,246945.0,0.001073,0.032741,0.0,0.0,0.0,0.0,1.0
pus_in_urine,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
abnormal_size_or_shape_of_ear,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
low_back_weakness,246945.0,0.000020,0.004500,0.0,0.0,0.0,0.0,1.0
sleepiness,246945.0,0.011529,0.106752,0.0,0.0,0.0,0.0,1.0
apnea,246945.0,0.006589,0.080902,0.0,0.0,0.0,0.0,1.0
abnormal_breathing_sounds,246945.0,0.010913,0.103896,0.0,0.0,0.0,0.0,1.0
excessive_growth,246945.0,0.000146,0.012073,0.0,0.0,0.0,0.0,1.0
elbow_cramps_or_spasms,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
feeling_hot_and_cold,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
blood_clots_during_menstrual_periods,246945.0,0.010946,0.104048,0.0,0.0,0.0,0.0,1.0
absence_of_menstruation,246945.0,0.002369,0.048614,0.0,0.0,0.0,0.0,1.0
pulling_at_ears,246945.0,0.014343,0.118902,0.0,0.0,0.0,0.0,1.0
gum_pain,246945.0,0.008682,0.092773,0.0,0.0,0.0,0.0,1.0
redness_in_ear,246945.0,0.012238,0.109945,0.0,0.0,0.0,0.0,1.0
fluid_retention,246945.0,0.017141,0.129799,0.0,0.0,0.0,0.0,1.0
flu_like_syndrome,246945.0,0.004236,0.064945,0.0,0.0,0.0,0.0,1.0
sinus_congestion,246945.0,0.009468,0.096841,0.0,0.0,0.0,0.0,1.0
painful_sinuses,246945.0,0.009674,0.097881,0.0,0.0,0.0,0.0,1.0
fears_and_phobias,246945.0,0.016813,0.128572,0.0,0.0,0.0,0.0,1.0
recent_pregnancy,246945.0,0.002912,0.053881,0.0,0.0,0.0,0.0,1.0
uterine_contractions,246945.0,0.005596,0.074600,0.0,0.0,0.0,0.0,1.0
burning_chest_pain,246945.0,0.003021,0.054880,0.0,0.0,0.0,0.0,1.0
back_cramps_or_spasms,246945.0,0.005175,0.071753,0.0,0.0,0.0,0.0,1.0
stiffness_all_over,246945.0,0.003989,0.063031,0.0,0.0,0.0,0.0,1.0
muscle_cramps_contractures_or_spasms,246945.0,0.003487,0.058945,0.0,0.0,0.0,0.0,1.0
low_back_cramps_or_spasms,246945.0,0.000417,0.020419,0.0,0.0,0.0,0.0,1.0
back_mass_or_lump,246945.0,0.005985,0.077132,0.0,0.0,0.0,0.0,1.0
nosebleed,246945.0,0.006038,0.077468,0.0,0.0,0.0,0.0,1.0
long_menstrual_periods,246945.0,0.010213,0.100541,0.0,0.0,0.0,0.0,1.0
heavy_menstrual_flow,246945.0,0.014084,0.117838,0.0,0.0,0.0,0.0,1.0
unpredictable_menstruation,246945.0,0.009391,0.096450,0.0,0.0,0.0,0.0,1.0
painful_menstruation,246945.0,0.008532,0.091976,0.0,0.0,0.0,0.0,1.0
infertility,246945.0,0.004823,0.069280,0.0,0.0,0.0,0.0,1.0
frequent_menstruation,246945.0,0.003827,0.061742,0.0,0.0,0.0,0.0,1.0
sweating,246945.0,0.015210,0.122387,0.0,0.0,0.0,0.0,1.0
mass_on_eyelid,246945.0,0.004697,0.068377,0.0,0.0,0.0,0.0,1.0
swollen_eye,246945.0,0.019024,0.136611,0.0,0.0,0.0,0.0,1.0
eyelid_swelling,246945.0,0.006637,0.081198,0.0,0.0,0.0,0.0,1.0
eyelid_lesion_or_rash,246945.0,0.002065,0.045398,0.0,0.0,0.0,0.0,1.0
unwanted_hair,246945.0,0.000089,0.009438,0.0,0.0,0.0,0.0,1.0
symptoms_of_bladder,246945.0,0.011735,0.107693,0.0,0.0,0.0,0.0,1.0
irregular_appearing_nails,246945.0,0.008204,0.090205,0.0,0.0,0.0,0.0,1.0
itching_of_skin,246945.0,0.041965,0.200509,0.0,0.0,0.0,0.0,1.0
hurts_to_breath,246945.0,0.010027,0.099629,0.0,0.0,0.0,0.0,1.0
nailbiting,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
skin_dryness_peeling_scaliness_or_roughness,246945.0,0.031857,0.175620,0.0,0.0,0.0,0.0,1.0
skin_on_arm_or_hand_looks_infected,246945.0,0.002017,0.044862,0.0,0.0,0.0,0.0,1.0
skin_irritation,246945.0,0.019648,0.138788,0.0,0.0,0.0,0.0,1.0
itchy_scalp,246945.0,0.007386,0.085626,0.0,0.0,0.0,0.0,1.0
hip_swelling,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
incontinence_of_stool,246945.0,0.000036,0.006037,0.0,0.0,0.0,0.0,1.0
foot_or_toe_cramps_or_spasms,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
warts,246945.0,0.011865,0.108279,0.0,0.0,0.0,0.0,1.0
bumps_on_penis,246945.0,0.001385,0.037189,0.0,0.0,0.0,0.0,1.0
too_little_hair,246945.0,0.005090,0.071164,0.0,0.0,0.0,0.0,1.0
foot_or_toe_lump_or_mass,246945.0,0.000146,0.012073,0.0,0.0,0.0,0.0,1.0
skin_rash,246945.0,0.050112,0.218177,0.0,0.0,0.0,0.0,1.0
mass_or_swelling_around_the_anus,246945.0,0.001863,0.043120,0.0,0.0,0.0,0.0,1.0
low_back_swelling,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
ankle_swelling,246945.0,0.008419,0.091368,0.0,0.0,0.0,0.0,1.0
hip_lump_or_mass,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
drainage_in_throat,246945.0,0.000405,0.020119,0.0,0.0,0.0,0.0,1.0
dry_or_flaky_scalp,246945.0,0.001855,0.043026,0.0,0.0,0.0,0.0,1.0
premenstrual_tension_or_irritability,246945.0,0.000247,0.015715,0.0,0.0,0.0,0.0,1.0
feeling_hot,246945.0,0.000004,0.002012,0.0,0.0,0.0,0.0,1.0
feet_turned_in,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
foot_or_toe_stiffness_or_tightness,246945.0,0.001267,0.035579,0.0,0.0,0.0,0.0,1.0
pelvic_pressure,246945.0,0.000081,0.008999,0.0,0.0,0.0,0.0,1.0
elbow_swelling,246945.0,0.008050,0.089362,0.0,0.0,0.0,0.0,1.0
elbow_stiffness_or_tightness,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
early_or_late_onset_of_menopause,246945.0,0.000830,0.028800,0.0,0.0,0.0,0.0,1.0
mass_on_ear,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
bleeding_from_ear,246945.0,0.002786,0.052710,0.0,0.0,0.0,0.0,1.0
hand_or_finger_weakness,246945.0,0.003280,0.057178,0.0,0.0,0.0,0.0,1.0
low_self_esteem,246945.0,0.010670,0.102745,0.0,0.0,0.0,0.0,1.0
throat_irritation,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
itching_of_the_anus,246945.0,0.003778,0.061351,0.0,0.0,0.0,0.0,1.0
swollen_or_red_tonsils,246945.0,0.002754,0.052403,0.0,0.0,0.0,0.0,1.0
irregular_belly_button,246945.0,0.000968,0.031095,0.0,0.0,0.0,0.0,1.0
swollen_tongue,246945.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
lip_sore,246945.0,0.000397,0.019917,0.0,0.0,0.0,0.0,1.0
vulvar_sore,246945.0,0.000393,0.019815,0.0,0.0,0.0,0.0,1.0
hip_stiffness_or_tightness,246945.0,0.002478,0.049721,0.0,0.0,0.0,0.0,1.0
mouth_pain,246945.0,0.010156,0.100265,0.0,0.0,0.0,0.0,1.0

In [8]:
df.isna().sum()

diseases                                       0
anxiety_and_nervousness                        0
depression                                     0
shortness_of_breath                            0
depressive_or_psychotic_symptoms               0
sharp_chest_pain                               0
dizziness                                      0
insomnia                                       0
abnormal_involuntary_movements                 0
chest_tightness                                0
palpitations                                   0
irregular_heartbeat                            0
breathing_fast                                 0
hoarse_voice                                   0
sore_throat                                    0
difficulty_speaking                            0
cough                                          0
nasal_congestion                               0
throat_swelling                                0
diminished_hearing                             0
lump_in_throat                                 0
throat_feels_tight                             0
difficulty_in_swallowing                       0
skin_swelling                                  0
retention_of_urine                             0
groin_mass                                     0
leg_pain                                       0
hip_pain                                       0
suprapubic_pain                                0
blood_in_stool                                 0
lack_of_growth                                 0
emotional_symptoms                             0
elbow_weakness                                 0
back_weakness                                  0
pus_in_sputum                                  0
symptoms_of_the_scrotum_and_testes             0
swelling_of_scrotum                            0
pain_in_testicles                              0
flatulence                                     0
pus_draining_from_ear                          0
jaundice                                       0
mass_in_scrotum                                0
white_discharge_from_eye                       0
irritable_infant                               0
abusing_alcohol                                0
fainting                                       0
hostile_behavior                               0
drug_abuse                                     0
sharp_abdominal_pain                           0
feeling_ill                                    0
vomiting                                       0
headache                                       0
nausea                                         0
diarrhea                                       0
vaginal_itching                                0
vaginal_dryness                                0
painful_urination                              0
involuntary_urination                          0
pain_during_intercourse                        0
frequent_urination                             0
lower_abdominal_pain                           0
vaginal_discharge                              0
blood_in_urine                                 0
hot_flashes                                    0
intermenstrual_bleeding                        0
hand_or_finger_pain                            0
wrist_pain                                     0
hand_or_finger_swelling                        0
arm_pain                                       0
wrist_swelling                                 0
arm_stiffness_or_tightness                     0
arm_swelling                                   0
hand_or_finger_stiffness_or_tightness          0
wrist_stiffness_or_tightness                   0
lip_swelling                                   0
toothache                                      0
abnormal_appearing_skin                        0
skin_lesion                                    0
acne_or_pimples                                0
dry_lips                                       0
facial_pain                                    0
mouth_ulcer                                    0
skin_growth                                    0
eye_deviation                                  0
diminished_vision                              0
double_vision                                  0
cross_eyed                                     0
symptoms_of_eye                                0
pain_in_eye                                    0
eye_moves_abnormally                           0
abnormal_movement_of_eyelid                    0
foreign_body_sensation_in_eye                  0
irregular_appearing_scalp                      0
swollen_lymph_nodes                            0
back_pain                                      0
neck_pain                                      0
low_back_pain                                  0
pain_of_the_anus                               0
pain_during_pregnancy                          0
pelvic_pain                                    0
impotence                                      0
infant_spitting_up                             0
vomiting_blood                                 0
regurgitation                                  0
burning_abdominal_pain                         0
restlessness                                   0
symptoms_of_infants                            0
wheezing                                       0
peripheral_edema                               0
neck_mass                                      0
ear_pain                                       0
jaw_swelling                                   0
mouth_dryness                                  0
neck_swelling                                  0
knee_pain                                      0
foot_or_toe_pain                               0
bowlegged_or_knock_kneed                       0
ankle_pain                                     0
bones_are_painful                              0
knee_weakness                                  0
elbow_pain                                     0
knee_swelling                                  0
skin_moles                                     0
knee_lump_or_mass                              0
weight_gain                                    0
problems_with_movement                         0
knee_stiffness_or_tightness                    0
leg_swelling                                   0
foot_or_toe_swelling                           0
heartburn                                      0
smoking_problems                               0
muscle_pain                                    0
infant_feeding_problem                         0
recent_weight_loss                             0
problems_with_shape_or_size_of_breast          0
underweight                                    0
difficulty_eating                              0
scanty_menstrual_flow                          0
vaginal_pain                                   0
vaginal_redness                                0
vulvar_irritation                              0
weakness                                       0
decreased_heart_rate                           0
increased_heart_rate                           0
bleeding_or_discharge_from_nipple              0
ringing_in_ear                                 0
plugged_feeling_in_ear                         0
itchy_ear_s_                                   0
frontal_headache                               0
fluid_in_ear                                   0
neck_stiffness_or_tightness                    0
spots_or_clouds_in_vision                      0
eye_redness                                    0
lacrimation                                    0
itchiness_of_eye                               0
blindness                                      0
eye_burns_or_stings                            0
itchy_eyelid                                   0
feeling_cold                                   0
decreased_appetite                             0
excessive_appetite                             0
excessive_anger                                0
loss_of_sensation                              0
focal_weakness                                 0
slurring_words                                 0
symptoms_of_the_face                           0
disturbance_of_memory                          0
paresthesia                                    0
side_pain                                      0
fever                                          0
shoulder_pain                                  0
shoulder_stiffness_or_tightness                0
shoulder_weakness                              0
arm_cramps_or_spasms                           0
shoulder_swelling                              0
tongue_lesions                                 0
leg_cramps_or_spasms                           0
abnormal_appearing_tongue                      0
ache_all_over                                  0
lower_body_pain                                0
problems_during_pregnancy                      0
spotting_or_bleeding_during_pregnancy          0
cramps_and_spasms                              0
upper_abdominal_pain                           0
stomach_bloating                               0
changes_in_stool_appearance                    0
unusual_color_or_odor_to_urine                 0
kidney_mass                                    0
swollen_abdomen                                0
symptoms_of_prostate                           0
leg_stiffness_or_tightness                     0
difficulty_breathing                           0
rib_pain                                       0
joint_pain                                     0
muscle_stiffness_or_tightness                  0
pallor                                         0
hand_or_finger_lump_or_mass                    0
chills                                         0
groin_pain                                     0
fatigue                                        0
abdominal_distention                           0
regurgitation_1                                0
symptoms_of_the_kidneys                        0
melena                                         0
flushing                                       0
coughing_up_sputum                             0
seizures                                       0
delusions_or_hallucinations                    0
shoulder_cramps_or_spasms                      0
joint_stiffness_or_tightness                   0
pain_or_soreness_of_breast                     0
excessive_urination_at_night                   0
bleeding_from_eye                              0
rectal_bleeding                                0
constipation                                   0
temper_problems                                0
coryza                                         0
wrist_weakness                                 0
eye_strain                                     0
hemoptysis                                     0
lymphedema                                     0
skin_on_leg_or_foot_looks_infected             0
allergic_reaction                              0
congestion_in_chest                            0
muscle_swelling                                0
pus_in_urine                                   0
abnormal_size_or_shape_of_ear                  0
low_back_weakness                              0
sleepiness                                     0
apnea                                          0
abnormal_breathing_sounds                      0
excessive_growth                               0
elbow_cramps_or_spasms                         0
feeling_hot_and_cold                           0
blood_clots_during_menstrual_periods           0
absence_of_menstruation                        0
pulling_at_ears                                0
gum_pain                                       0
redness_in_ear                                 0
fluid_retention                                0
flu_like_syndrome                              0
sinus_congestion                               0
painful_sinuses                                0
fears_and_phobias                              0
recent_pregnancy                               0
uterine_contractions                           0
burning_chest_pain                             0
back_cramps_or_spasms                          0
stiffness_all_over                             0
muscle_cramps_contractures_or_spasms           0
low_back_cramps_or_spasms                      0
back_mass_or_lump                              0
nosebleed                                      0
long_menstrual_periods                         0
heavy_menstrual_flow                           0
unpredictable_menstruation                     0
painful_menstruation                           0
infertility                                    0
frequent_menstruation                          0
sweating                                       0
mass_on_eyelid                                 0
swollen_eye                                    0
eyelid_swelling                                0
eyelid_lesion_or_rash                          0
unwanted_hair                                  0
symptoms_of_bladder                            0
irregular_appearing_nails                      0
itching_of_skin                                0
hurts_to_breath                                0
nailbiting                                     0
skin_dryness_peeling_scaliness_or_roughness    0
skin_on_arm_or_hand_looks_infected             0
skin_irritation                                0
itchy_scalp                                    0
hip_swelling                                   0
incontinence_of_stool                          0
foot_or_toe_cramps_or_spasms                   0
warts                                          0
bumps_on_penis                                 0
too_little_hair                                0
foot_or_toe_lump_or_mass                       0
skin_rash                                      0
mass_or_swelling_around_the_anus               0
low_back_swelling                              0
ankle_swelling                                 0
hip_lump_or_mass                               0
drainage_in_throat                             0
dry_or_flaky_scalp                             0
premenstrual_tension_or_irritability           0
feeling_hot                                    0
feet_turned_in                                 0
foot_or_toe_stiffness_or_tightness             0
pelvic_pressure                                0
elbow_swelling                                 0
elbow_stiffness_or_tightness                   0
early_or_late_onset_of_menopause               0
mass_on_ear                                    0
bleeding_from_ear                              0
hand_or_finger_weakness                        0
low_self_esteem                                0
throat_irritation                              0
itching_of_the_anus                            0
swollen_or_red_tonsils                         0
irregular_belly_button                         0
swollen_tongue                                 0
lip_sore                                       0
vulvar_sore                                    0
hip_stiffness_or_tightness                     0
mouth_pain                                     0
arm_weakness                                   0
leg_lump_or_mass                               0
disturbance_of_smell_or_taste                  0
discharge_in_stools                            0
penis_pain                                     0
loss_of_sex_drive                              0
obsessions_and_compulsions                     0
antisocial_behavior                            0
neck_cramps_or_spasms                          0
pupils_unequal                                 0
poor_circulation                               0
thirst                                         0
sleepwalking                                   0
skin_oiliness                                  0
sneezing                                       0
bladder_mass                                   0
knee_cramps_or_spasms                          0
premature_ejaculation                          0
leg_weakness                                   0
posture_problems                               0
bleeding_in_mouth                              0
tongue_bleeding                                0
change_in_skin_mole_size_or_color              0
penis_redness                                  0
penile_discharge                               0
shoulder_lump_or_mass                          0
polyuria                                       0
cloudy_eye                                     0
hysterical_behavior                            0
arm_lump_or_mass                               0
nightmares                                     0
bleeding_gums                                  0
pain_in_gums                                   0
bedwetting                                     0
diaper_rash                                    0
lump_or_mass_of_breast                         0
vaginal_bleeding_after_menopause               0
infrequent_menstruation                        0
mass_on_vulva                                  0
jaw_pain                                       0
itching_of_scrotum                             0
postpartum_problems_of_the_breast              0
eyelid_retracted                               0
hesitancy                                      0
elbow_lump_or_mass                             0
muscle_weakness                                0
throat_redness                                 0
joint_swelling                                 0
tongue_pain                                    0
redness_in_or_around_nose                      0
wrinkles_on_skin                               0
foot_or_toe_weakness                           0
hand_or_finger_cramps_or_spasms                0
back_stiffness_or_tightness                    0
wrist_lump_or_mass                             0
skin_pain                                      0
low_back_stiffness_or_tightness                0
low_urine_output                               0
skin_on_head_or_neck_looks_infected            0
stuttering_or_stammering                       0
problems_with_orgasm                           0
nose_deformity                                 0
lump_over_jaw                                  0
sore_in_nose                                   0
hip_weakness                                   0
back_swelling                                  0
ankle_stiffness_or_tightness                   0
ankle_weakness                                 0
neck_weakness                                  0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.duplicated().sum()

np.int64(57305)

In [11]:
df['diseases'].value_counts()

diseases
cystitis                                                    1219
vulvodynia                                                  1218
nose disorder                                               1218
complex regional pain syndrome                              1217
spondylosis                                                 1216
hypoglycemia                                                1215
conjunctivitis due to allergy                               1215
vaginal cyst                                                1215
esophagitis                                                 1215
peripheral nerve disorder                                   1215
gastrointestinal hemorrhage                                 1214
diverticulitis                                              1214
acute bronchitis                                            1213
infectious gastroenteritis                                  1212
pneumonia                                                   1212
fungal infection of the hair                                1212
sprain or strain                                            1212
spontaneous abortion                                        1212
gout                                                        1211
marijuana abuse                                             1210
arthritis of the hip                                        1210
strep throat                                                1210
injury to the arm                                           1209
liver disease                                               1209
bursitis                                                    1208
acute pancreatitis                                          1207
spinal stenosis                                             1207
eczema                                                      1207
injury to the leg                                           1206
noninfectious gastroenteritis                               1206
benign prostatic hyperplasia (bph)                          1206
acute bronchiolitis                                         1204
cholecystitis                                               1204
anxiety                                                     1198
obstructive sleep apnea (osa)                               1196
concussion                                                  1191
dental caries                                               1185
problem during pregnancy                                     913
sickle cell crisis                                           913
chronic constipation                                         913
sebaceous cyst                                               913
psoriasis                                                    912
depression                                                   912
hyperemesis gravidarum                                       912
pyogenic skin infection                                      911
personality disorder                                         911
developmental disability                                     911
otitis media                                                 910
seasonal allergies (hay fever)                               910
urinary tract infection                                      910
multiple sclerosis                                           910
acute stress reaction                                        910
panic disorder                                               909
vaginitis                                                    909
actinic keratosis                                            909
degenerative disc disease                                    909
drug reaction                                                909
macular degeneration                                         909
sepsis                                                       909
contact dermatitis                                           909
sinus bradycardia                                            909
eustachian tube dysfunction (ear disorder)                   909
skin pigmentation disorder                                   909
conjunctivitis                                               909
pain after an operation                                      908
acute kidney injury                                          908
stye                                                         908
idiopathic irregular menstrual cycle                         908
hemorrhoids                                                  908
herniated disk                                               908
heart attack                                                 907
ear drum damage                                              907
brachial neuritis                                            907
acute sinusitis                                              906
chronic obstructive pulmonary disease (copd)                 906
hiatal hernia                                                906
acute bronchospasm                                           906
idiopathic excessive menstruation                            906
blepharitis                                                  906
idiopathic painful menstruation                              906
angina                                                       906
injury to the trunk                                          905
allergy                                                      905
threatened pregnancy                                         905
common cold                                                  905
asthma                                                       904
kidney stone                                                 904
otitis externa (swimmer's ear)                               904
croup                                                        904
gallstone                                                    904
pyelonephritis                                               903
cornea infection                                             903
appendicitis                                                 903
heart failure                                                903
hypertensive heart disease                                   902
rectal disorder                                              902
psychotic disorder                                           902
neurosis                                                     902
pelvic inflammatory disease                                  900
chronic back pain                                            899
temporary or benign blood in urine                           897
skin polyp                                                   897
diaper rash                                                  897
osteoarthritis                                               896
carpal tunnel syndrome                                       896
gum disease                                                  894
schizophrenia                                                890
ischemic heart disease                                       886
smoking or tobacco addiction                                 883
fracture of the rib                                          882
seborrheic dermatitis                                        880
pulmonary embolism                                           880
seborrheic keratosis                                         870
dry eye of unknown cause                                     861
bell palsy                                                   685
neuralgia                                                    684
lipoma                                                       684
acute otitis media                                           683
fungal infection of the skin                                 683
iron deficiency anemia                                       683
urinary tract obstruction                                    683
impetigo                                                     683
gastroduodenal ulcer                                         683
varicocele of the testicles                                  682
benign vaginal discharge (leukorrhea)                        682
oral thrush (yeast infection)                                681
sensorineural hearing loss                                   681
prostatitis                                                  681
conjunctivitis due to virus                                  681
flu                                                          679
gastritis                                                    679
conduct disorder                                             679
chalazion                                                    678
muscle spasm                                                 678
fracture of the leg                                          678
tendinitis                                                   678
rheumatoid arthritis                                         678
ear wax impaction                                            678
rosacea                                                      678
laryngitis                                                   678
chronic pain disorder                                        677
corneal disorder                                             676
skin disorder                                                676
mononeuritis                                                 676
hemangioma                                                   676
ganglion cyst                                                675
diverticulosis                                               673
diabetic ketoacidosis                                        673
spondylolisthesis                                            673
tooth disorder                                               671
paroxysmal ventricular tachycardia                           671
chronic otitis media                                         669
tooth abscess                                                669
insect bite                                                  669
sciatica                                                     668
chronic glaucoma                                             668
alcohol withdrawal                                           665
bipolar disorder                                             663
skin cancer                                                  661
hyperkalemia                                                 657
chronic sinusitis                                            657
fibromyalgia                                                 656
transient ischemic attack                                    655
labyrinthitis                                                654
stroke                                                       642
vaginal yeast infection                                      608
cataract                                                     607
post-traumatic stress disorder (ptsd)                        607
pleural effusion                                             607
deviated nasal septum                                        607
heart block                                                  606
oral mucosal lesion                                          606
erectile dysfunction                                         606
ankylosing spondylitis                                       606
ingrown toe nail                                             604
drug abuse (opioids)                                         604
intracerebral hemorrhage                                     603
drug abuse                                                   603
viral exanthem                                               601
conductive hearing loss                                      598
delirium                                                     598
parkinson disease                                            513
callus                                                       513
interstitial lung disease                                    511
social phobia                                                511
epididymitis                                                 511
molluscum contagiosum                                        511
injury to the shoulder                                       510
alcohol abuse                                                510
irritable bowel syndrome                                     510
sialoadenitis                                                509
attention deficit hyperactivity disorder (adhd)              507
lymphedema                                                   505
onychomycosis                                                505
mitral valve disease                                         504
itching of unknown cause                                     504
hemiplegia                                                   504
white blood cell disease                                     504
adjustment reaction                                          503
breast infection (mastitis)                                  501
corneal abrasion                                             500
dysthymic disorder                                           499
ovarian cyst                                                 499
glaucoma                                                     498
pulmonary congestion                                         497
acne                                                         496
iridocyclitis                                                496
urge incontinence                                            495
hyponatremia                                                 495
eating disorder                                              494
postpartum depression                                        494
idiopathic absence of menstruation                           493
hypokalemia                                                  478
yeast infection                                              470
diabetic retinopathy                                         456
envenomation from spider or animal bite                      455
injury to the face                                           455
bladder disorder                                             454
food allergy                                                 454
balanitis                                                    454
obsessive compulsive disorder (ocd)                          454
eye alignment disorder                                       453
viral warts                                                  453
urethritis                                                   453
lymphadenitis                                                453
autism                                                       452
diabetic peripheral neuropathy                               452
thrombophlebitis                                             451
spondylitis                                                  451
acute respiratory distress syndrome (ards)                   451
aortic valve disease                                         451
uterine fibroids                                             450
herpangina                                                   450
joint effusion                                               449
ileus                                                        449
fracture of the facial bones                                 449
gastroesophageal reflux disease (gerd)                       448
myopia                                                       448
indigestion                                                  447
dermatitis due to sun exposure                               446
pulmonary hypertension                                       446
tonsillitis                                                  446
intestinal obstruction                                       445
benign paroxysmal positional vertical (bppv)                 443
choledocholithiasis                                          441
teething syndrome                                            438
pelvic organ prolapse                                        438
atrophic skin condition                                      438
paronychia                                                   438
fracture of the arm                                          437
oppositional disorder                                        431
hypovolemia                                                  424
abdominal hernia                                             407
inguinal hernia                                              402
pain disorder affecting the neck                             387
cervicitis                                                   384
intestinal disease                                           383
athlete's foot                                               382
peritonitis                                                  381
shingles (herpes zoster)                                     379
endometriosis                                                378
osteoporosis                                                 378
ulcerative colitis                                           377
crohn disease                                                376
paroxysmal supraventricular tachycardia                      375
missed abortion                                              375
hepatitis due to a toxin                                     357
nasal polyp                                                  356
alcohol intoxication                                         351
cardiac arrest                                               346
temporomandibular joint disorder                             341
ectopic pregnancy                                            341
vitreous degeneration                                        341
abscess of the pharynx                                       341
alopecia                                                     340
cranial nerve palsy                                          340
hydronephrosis                                               340
pilonidal cyst                                               339
colonic polyp                                                339
dementia                                                     339
trichomonas infection                                        339
tonsillar hypertrophy                                        339
scleroderma                                                  338
bladder obstruction                                          338
asperger syndrome                                            338
lateral epicondylitis (tennis elbow)                         337
alzheimer disease                                            336
venous insufficiency                                         336
jaw disorder                                                 336
impulse control disorder                                     335
tietze syndrome                                              333
cirrhosis                                                    331
mononucleosis                                                331
anemia                                                       331
drug abuse (methamphetamine)                                 330
sarcoidosis                                                  330
atrophic vaginitis                                           329
fluid overload                                               327
head and neck cancer                                         326
premature ventricular contractions (pvcs)                    325
intracranial hemorrhage                                      322
astigmatism                                                  321
urethral disorder                                            315
cardiomyopathy                                               311
vasculitis                                                   299
meningitis                                                   297
chronic pancreatitis                                         297

In [12]:
df = df.drop_duplicates()

In [13]:
df.shape

(189640, 378)

In [14]:
constant_cols = df.columns[df.nunique() <= 1].tolist()

print("Constant columns:", constant_cols)
print("Number of constant columns:", len(constant_cols))

Constant columns: ['pus_in_sputum', 'underweight', 'arm_cramps_or_spasms', 'abnormal_appearing_tongue', 'pallor', 'shoulder_cramps_or_spasms', 'joint_stiffness_or_tightness', 'eye_strain', 'pus_in_urine', 'abnormal_size_or_shape_of_ear', 'elbow_cramps_or_spasms', 'feeling_hot_and_cold', 'nailbiting', 'hip_swelling', 'foot_or_toe_cramps_or_spasms', 'low_back_swelling', 'hip_lump_or_mass', 'feet_turned_in', 'elbow_stiffness_or_tightness', 'mass_on_ear', 'throat_irritation', 'swollen_tongue', 'disturbance_of_smell_or_taste', 'discharge_in_stools', 'pupils_unequal', 'sleepwalking', 'skin_oiliness', 'knee_cramps_or_spasms', 'posture_problems', 'bleeding_in_mouth', 'tongue_bleeding', 'change_in_skin_mole_size_or_color', 'polyuria', 'infrequent_menstruation', 'mass_on_vulva', 'jaw_pain', 'eyelid_retracted', 'elbow_lump_or_mass', 'tongue_pain', 'low_back_stiffness_or_tightness', 'skin_on_head_or_neck_looks_infected', 'stuttering_or_stammering', 'problems_with_orgasm', 'nose_deformity', 'lump_over_jaw', 'hip_weakness', 'back_swelling', 'ankle_stiffness_or_tightness', 'neck_weakness']
Number of constant columns: 49

In [15]:
df = df.drop(columns=constant_cols)

In [16]:
df.shape

(189640, 329)

In [17]:
df.to_csv("../data/processed/cleaned_data.csv",index=False)